/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const RoomMessage = IDL.Text;
export const MessageTimestamp = IDL.Int;
export const SenderName = IDL.Text;
export const ChatRoomId = IDL.Nat;
export const ChatMessage = IDL.Record({
  'message' : RoomMessage,
  'timestamp' : MessageTimestamp,
  'senderName' : SenderName,
  'roomId' : ChatRoomId,
});
export const UserProfile = IDL.Record({
  'displayName' : IDL.Text,
  'avatarUrl' : IDL.Text,
});
export const RoomId = IDL.Nat;
export const Time = IDL.Int;
export const RoomTitle = IDL.Text;
export const ThumbnailURL = IDL.Text;
export const HostName = IDL.Text;
export const ViewerCount = IDL.Nat;
export const Room = IDL.Record({
  'id' : RoomId,
  'startTime' : Time,
  'title' : RoomTitle,
  'thumbnailUrl' : ThumbnailURL,
  'hostName' : HostName,
  'isActive' : IDL.Bool,
  'viewerCount' : ViewerCount,
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'createRoom' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [IDL.Nat], []),
  'getAllMessages' : IDL.Func([], [IDL.Vec(ChatMessage)], ['query']),
  'getAllProfiles' : IDL.Func([], [IDL.Vec(UserProfile)], ['query']),
  'getAllRooms' : IDL.Func([], [IDL.Vec(Room)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getChatMessages' : IDL.Func([IDL.Nat], [IDL.Vec(ChatMessage)], ['query']),
  'getLiveRooms' : IDL.Func([], [IDL.Vec(Room)], ['query']),
  'getMessagesByRoom' : IDL.Func([IDL.Nat], [IDL.Vec(ChatMessage)], ['query']),
  'getProfile' : IDL.Func([IDL.Principal], [UserProfile], ['query']),
  'getRoom' : IDL.Func([IDL.Nat], [Room], ['query']),
  'getTotalRooms' : IDL.Func([], [IDL.Nat], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'joinRoom' : IDL.Func([IDL.Nat], [], []),
  'saveCallerUserProfile' : IDL.Func([IDL.Text, IDL.Text], [], []),
  'sendChatMessage' : IDL.Func([IDL.Nat, IDL.Text, IDL.Text], [], []),
  'updateProfile' : IDL.Func([IDL.Text, IDL.Text], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const RoomMessage = IDL.Text;
  const MessageTimestamp = IDL.Int;
  const SenderName = IDL.Text;
  const ChatRoomId = IDL.Nat;
  const ChatMessage = IDL.Record({
    'message' : RoomMessage,
    'timestamp' : MessageTimestamp,
    'senderName' : SenderName,
    'roomId' : ChatRoomId,
  });
  const UserProfile = IDL.Record({
    'displayName' : IDL.Text,
    'avatarUrl' : IDL.Text,
  });
  const RoomId = IDL.Nat;
  const Time = IDL.Int;
  const RoomTitle = IDL.Text;
  const ThumbnailURL = IDL.Text;
  const HostName = IDL.Text;
  const ViewerCount = IDL.Nat;
  const Room = IDL.Record({
    'id' : RoomId,
    'startTime' : Time,
    'title' : RoomTitle,
    'thumbnailUrl' : ThumbnailURL,
    'hostName' : HostName,
    'isActive' : IDL.Bool,
    'viewerCount' : ViewerCount,
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'createRoom' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [IDL.Nat], []),
    'getAllMessages' : IDL.Func([], [IDL.Vec(ChatMessage)], ['query']),
    'getAllProfiles' : IDL.Func([], [IDL.Vec(UserProfile)], ['query']),
    'getAllRooms' : IDL.Func([], [IDL.Vec(Room)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getChatMessages' : IDL.Func([IDL.Nat], [IDL.Vec(ChatMessage)], ['query']),
    'getLiveRooms' : IDL.Func([], [IDL.Vec(Room)], ['query']),
    'getMessagesByRoom' : IDL.Func(
        [IDL.Nat],
        [IDL.Vec(ChatMessage)],
        ['query'],
      ),
    'getProfile' : IDL.Func([IDL.Principal], [UserProfile], ['query']),
    'getRoom' : IDL.Func([IDL.Nat], [Room], ['query']),
    'getTotalRooms' : IDL.Func([], [IDL.Nat], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'joinRoom' : IDL.Func([IDL.Nat], [], []),
    'saveCallerUserProfile' : IDL.Func([IDL.Text, IDL.Text], [], []),
    'sendChatMessage' : IDL.Func([IDL.Nat, IDL.Text, IDL.Text], [], []),
    'updateProfile' : IDL.Func([IDL.Text, IDL.Text], [], []),
  });
};

export const init = ({ IDL }) => { return []; };