/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface ChatMessage {
  'message' : RoomMessage,
  'timestamp' : MessageTimestamp,
  'senderName' : SenderName,
  'roomId' : ChatRoomId,
}
export type ChatRoomId = bigint;
export type HostName = string;
export type MessageTimestamp = bigint;
export interface Room {
  'id' : RoomId,
  'startTime' : Time,
  'title' : RoomTitle,
  'thumbnailUrl' : ThumbnailURL,
  'hostName' : HostName,
  'isActive' : boolean,
  'viewerCount' : ViewerCount,
}
export type RoomId = bigint;
export type RoomMessage = string;
export type RoomTitle = string;
export type SenderName = string;
export type ThumbnailURL = string;
export type Time = bigint;
export interface UserProfile { 'displayName' : string, 'avatarUrl' : string }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export type ViewerCount = bigint;
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'createRoom' : ActorMethod<[string, string, string], bigint>,
  'getAllMessages' : ActorMethod<[], Array<ChatMessage>>,
  'getAllProfiles' : ActorMethod<[], Array<UserProfile>>,
  'getAllRooms' : ActorMethod<[], Array<Room>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getChatMessages' : ActorMethod<[bigint], Array<ChatMessage>>,
  'getLiveRooms' : ActorMethod<[], Array<Room>>,
  'getMessagesByRoom' : ActorMethod<[bigint], Array<ChatMessage>>,
  'getProfile' : ActorMethod<[Principal], UserProfile>,
  'getRoom' : ActorMethod<[bigint], Room>,
  'getTotalRooms' : ActorMethod<[], bigint>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'joinRoom' : ActorMethod<[bigint], undefined>,
  'saveCallerUserProfile' : ActorMethod<[string, string], undefined>,
  'sendChatMessage' : ActorMethod<[bigint, string, string], undefined>,
  'updateProfile' : ActorMethod<[string, string], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];